FROM nvidia/cuda:12.1.1-runtime-ubuntu22.04

# Prevent Python from buffering logs
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# -----------------------------
# SYSTEM DEPENDENCIES
# -----------------------------
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# -----------------------------
# INSTALL PYTHON DEPENDENCIES
# -----------------------------
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# -----------------------------
# COPY APP
# -----------------------------
COPY . .

RUN pip install --no=cache-dir \
    fastapi \
    uvicorn \
    opencv-python \
    ultralytics \ 
    python-multipart

# -----------------------------
# CREATE TEMP DIRECTORY
# -----------------------------
RUN mkdir -p /app/temp

# -----------------------------
# EXPOSE PORT
# -----------------------------
EXPOSE 8000

# -----------------------------
# START SERVER
# -----------------------------
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
