FROM python:3.10-slim

WORKDIR /app

# Install system deps for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir fastapi uvicorn opencv-python ultralytics python-multipart

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
